# Generated by Django 5.2.7 on 2025-10-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='behab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleep', models.CharField(max_length=100)),
                ('read', models.TimeField()),
            ],
        ),
    ]
